"""add photo place table

Revision ID: ed892ca195ee
Revises: fe8659f7ce12
Create Date: 2023-06-25 14:57:51.935606

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed892ca195ee"
down_revision = "fe8659f7ce12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo_place",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column(
            "country",
            sqlalchemy_utils.types.country.CountryType(length=2),
            nullable=True,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    with op.batch_alter_table("photo_place", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_photo_place_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("photo_place", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_photo_place_name"))

    op.drop_table("photo_place")
    # ### end Alembic commands ###
