"""client added

Revision ID: fe8659f7ce12
Revises: e495eaae305e
Create Date: 2023-04-23 12:43:23.243656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe8659f7ce12"
down_revision = "e495eaae305e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("_phone_number", sa.Unicode(length=20), nullable=True),
        sa.Column("phone_country_code", sa.Unicode(length=8), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("contact_details", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_client_email"), ["email"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_client_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_name"))
        batch_op.drop_index(batch_op.f("ix_client_email"))

    op.drop_table("client")
    # ### end Alembic commands ###
